config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  post '/add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
  post '/increase_quantity', to: 'carts#increase_quantity', as: 'increase_quantity'
  post '/decrease_quantity', to: 'carts#decrease_quantity', as: 'decrease_quantity'
  post '/remove_from_cart', to: 'carts#remove_from_cart', as: 'remove_from_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  field :id, type: Integer
  field :image, type: String
  field :name, type: String
  field :description, type: String
  field :price, type: Float
  field :color, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_to_cart
    product_id = params[:product_id]
    session[:cart] ||= {}
    session[:cart][product_id.to_s] = (session[:cart][product_id.to_s] || 0) + 1
    calculate_cart_total
    redirect_to root_path
  end

  def increase_quantity
    product_id = params[:product_id]
    session[:cart][product_id.to_s] += 1
    calculate_cart_total
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def decrease_quantity
    product_id = params[:product_id]
    session[:cart][product_id.to_s] -= 1
    if session[:cart][product_id.to_s] <= 0
      session[:cart].delete(product_id.to_s)
    end
    calculate_cart_total
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def remove_from_cart
    product_id = params[:product_id]
    session[:cart].delete(product_id.to_s)
    calculate_cart_total
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def calculate_cart_total
    @cart_total = 0
    session[:cart]&.each do |product_id, quantity|
      product = Product.find(product_id)
      subtotal = product.price * quantity.to_i if quantity.is_a?(Numeric)
      @cart_total += subtotal.round(2) if subtotal
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @cart = session[:cart] || {}
    calculate_cart_total
  end

  private

  def calculate_cart_total
    @cart_total = 0
    session[:cart]&.each do |product_id, quantity|
      product = Product.find(product_id)
      @cart_total += product.price * quantity.to_i if quantity.is_a?(Numeric)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golden Sneaker</title>
    <link rel="icon" type="image/png" href="<%= asset_path('favicon.ico') %>">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Golden Sneaker</title>

    <style>
body {
        background-image: url("https://images.saymedia-content.com/.image/t_share/MTkzODU1MjgzMjUxMTkzMzI4/svg-wave-generator.gif");
        background-size: cover;
        background-repeat: no-repeat;
    }
        .container {
            display: flex;
            justify-content: space-around;
            margin-top: 50px;
            margin-left: 300px;
            margin-right: 300px;
        }

        .card {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            width: 360px;
            overflow-y: auto;
            height: 550px;
            padding-top: 0px;
            padding-left: 25px;
            padding-right: 25px;
            padding-bottom: 25px;
            border: 1px solid #ccc;
            margin: 5px;
            border-radius: 30px;
            background-color:#ffff;
        }

        .headproduct {
  /* height: auto; */
  position: sticky;
  top: 0;
  background-color: #fff;
  padding: 10px;
  /* margin-top: -100px; */
  z-index: 1;
}
.headcart {
    position: sticky;
    top: 0;
    background-color: #fff;
    padding: 10px;
    margin: 0;
    z-index: 1;
}



        .products,
        .cart {
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .product,
        .cart-product {
            margin-bottom: 20px;
        }

        .product h3,
        .cart-product h3 {
            margin: 10px 0;
        }

        .product img {
            max-width: 100%;
            height: auto;
            border-radius: 30px;
        }

        .product p,
        .cart-product p {
            margin-bottom: 5px;
        }

        .add-to-cart-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #22AFDC;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .add-to-cart-button:hover {
            background-color: #3569A1;
        }

        .card::-webkit-scrollbar {
            width: 0px;
        }

        .card::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        .card::-webkit-scrollbar-thumb {
            background: #888;
            border-radius: 4px;
        }

        .card::-webkit-scrollbar-thumb:hover {
            background: #555;
        }

        .product-footer {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .quantity-controls {
            display: flex;
            align-items: center;
        }

        .quantity-control-button {
            padding: 0 10px;
            background-color: #22AFDC;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .quantity-control-button:hover {
            background-color: #3569A1;
        }

        .quantity-control-icon {
            width: 20px;
            height: 20px;
        }

        .added-product {
            display: flex;
            align-items: center;
        }

        .check-mark {
            margin-left: 10px;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">

        <div class="headproduct">
                        <img src="/assets/nike.png" alt="image nike" style="width:70px;height:50px;padding-top:0px;margin-bottom:-30px">

            <h1>Our Products</h1>
        </div>
            <div class="products">
                <% @products.each do |product| %>
                    <div class="product">
                        <img src="<%= product.image %>" alt="<%= product.name %>" style="background-color: <%= product.color %>;">
                        <h3><%= product.name %></h3>
                        <p><%= product.description %></p>
                        <div class="product-footer">
                            <p><strong>Price:</strong> <%= product.price %></p>
                            <% if @cart[product.id.to_s] %>
                                <div class="added-product">

                                    <img src="/assets/check.png" alt="Checkmark" class="check-mark">
                                </div>
                            <% else %>
                                <%= form_with(url: add_to_cart_path, method: :post, local: true) do |form| %>
                                    <%= form.hidden_field :product_id, value: product.id %>
                                    <%= form.button type: :submit, class: 'add-to-cart-button' do %>
                                        Add To Cart
                                    <% end %>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="card"style="position: relative;">
<div class="headcart">
                     <img src="/assets/nike.png" alt="image nike" style="width: 70px; height: 50px; padding-top: 0px; margin-bottom: -30px;  top: 10px; left: 10px;">

            <div  style="display:flex;">

            <h1>Your Cart</h1>
            <h2 style="margin-left:80px;margin-top:30px;">$ <%= @cart_total %></h2></div>
</div>



            <div class="cart">
                <% if @cart.empty? %>
                    <p>Your cart is empty</p>
                    <% @cart_total = 0 %> <!-- Set total to 0 when the cart is empty -->
                <% else %>
                    <% @cart.each do |product_id, quantity| %>
                        <% product = Product.find(product_id) %>
                        <div class="cart-product">
                            <div style="display:flex;">

                            <img src="<%= product.image %>" alt="<%= product.name %>" style="background-color: <%= product.color %>;border-radius: 40%;width:79.96px;height:100px;">
                            <div style="margin-left:50px;margin-top:-10px;">
                            <h3><%= product.name %></h3>
                            <p><strong>Price:</strong> <%= product.price %></p>
<div style="display:flex;">
<div class="quantity-controls">
                                <%= form_with(url: increase_quantity_path, method: :post, local: true) do |form| %>
                                    <%= form.hidden_field :product_id, value: product.id %>
                                    <%= form.button type: :submit, class: 'quantity-control-button' do %>
                                        <%= image_tag('plus.png', alt: '+', class: 'quantity-control-icon') %>
                                    <% end %>
                                <% end %>
                                <span style="margin-left:10px;"><%= quantity %></span>
                                <div style="margin-left:10px;">
                                <%= form_with(url: decrease_quantity_path, method: :post, local: true) do |form| %>
                                    <%= form.hidden_field :product_id, value: product.id %>
                                    <%= form.button type: :submit, class: 'quantity-control-button' do %>
                                        <%= image_tag('minus.png', alt: '-', class: 'quantity-control-icon') %>
                                    <% end %>
                                <% end %>
                                </div>
                            </div>

                            <div style="margin-left:50px;" id="remove-form-<%= product.id %>">
                                <%= form_with(url: remove_from_cart_path, method: :post, remote: true, class: 'remove-form') do |form| %>
                                    <%= form.hidden_field :product_id, value: product.id %>
                                    <%= form.button type: :submit, class: 'quantity-control-button' do %>
                                        <%= image_tag('trash.png', alt: '-', class: 'quantity-control-icon') %>
                                    <% end %>
                                <% end %>
                            </div></div>
                            </div>
</div>


                        </div>
                    <% end %>
                <% end %>

            </div>
        </div>
    </div>

    <script>
        // Lắng nghe sự kiện tải xong trang
        window.addEventListener('load', function() {
            // Lấy danh sách thẻ card
            var cards = document.querySelectorAll('.card');

            // Lặp qua từng thẻ card và thêm tính năng kéo lên xuống
            cards.forEach(function(card) {
                card.addEventListener('mousedown', function(e) {
                    // Đảm bảo không làm kích hoạt sự kiện khi click vào các phần tử bên trong thẻ card
                    if (e.target === card) {
                        var start = card.scrollTop;
                        var startY = e.pageY;

                        // Lắng nghe sự kiện kéo chuột
                        card.addEventListener('mousemove', move);

                        // Lắng nghe sự kiện mouseup để kết thúc việc kéo
                        card.addEventListener('mouseup', function() {
                            card.removeEventListener('mousemove', move);
                        });

                        // Hàm xử lý sự kiện kéo chuột
                        function move(e) {
                            e.preventDefault();
                            var delta = startY - e.pageY;
                            card.scrollTop = start + delta;
                        }
                    }
                });
            });
        });
    </script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('.add-to-cart-button').click(function(e) {
      e.preventDefault();
      var form = $(this).closest('form');
      $.ajax({
        url: form.attr('action'),
        method: 'POST',
        dataType: 'script',
        data: form.serialize(),
        success: function(response) {
          // Xử lý khi thành công, có thể cập nhật giao diện giỏ hàng tại đây
        },
        error: function(xhr, status, error) {
          // Xử lý khi có lỗi xảy ra
        }
      });
    });
  });

    $('.quantity-control-button').click(function(e) {
      e.preventDefault();
      var form = $(this).closest('form');
      $.ajax({
        url: form.attr('action'),
        method: 'POST',
        dataType: 'script',
        data: form.serialize()
      });
    });

    $('.remove-form').submit(function(e) {
      e.preventDefault();
      var form = $(this);
      $.ajax({
        url: form.attr('action'),
        method: 'POST',
        dataType: 'script',
        data: form.serialize()
      });
    });
  });
</script>


</body>
</html>